// Custom icon static resources

import {
  InfoOutline,
  BulbOutline,
  ProfileOutline,
  ExceptionOutline,
  LinkOutline,
  HomeOutline,
  UserOutline,
  FolderOutline,
  ApartmentOutline,
  MoneyCollectOutline,
  DownSquareOutline,
  NotificationOutline,
  SafetyOutline,
  GoldOutline,
  PlusSquareOutline,
  MinusSquareOutline,
  GlobalOutline,
  StopOutline,
} from '@ant-design/icons-angular/icons';

export const ICONS = [
  InfoOutline,
  BulbOutline,
  ProfileOutline,
  ExceptionOutline,
  LinkOutline,
  HomeOutline,
  UserOutline,
  FolderOutline,
  ApartmentOutline,
  MoneyCollectOutline,
  DownSquareOutline,
  NotificationOutline,
  SafetyOutline,
  GoldOutline,
  PlusSquareOutline,
  MinusSquareOutline,
  GlobalOutline,
  StopOutline,
];
